src/Http/Controllers/PlatformController.php

This PR updates the version numbers returned in the platform's .well-known file to match the published release tags on GitHub.

[PLA-1408] Update .well-known version numbers to match their release tags.

---

src/Services/Database/CollectionService.php
src/Services/Database/TokenService.php
src/Services/Database/WalletService.php

bug_fix
___
- Removed global scopes from Eloquent queries across `CollectionService`, `TokenService`, and `WalletService` to ensure data integrity and accurate query results.
- This change affects various functions checking for the existence of attributes, accounts, tokens, and approvals, as well as wallet existence checks.
- Ensures that the application's data access layer operates correctly without being unintentionally filtered by global scopes.
___
<tr>
<td>
<details>
<summary><strong>CollectionService.php</strong><dd><code>Remove Global Scopes from Collection Queries</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

[PLA-1696] Remove scopes for rules in service classes.

---

src/GraphQL/Schemas/Primary/Mutations/MarkAndListPendingTransactionsMutation.php

bug_fix
___
- Refactored the SQL query within `MarkAndListPendingTransactionsMutation.php` to ensure correct filtering of transactions based on wallet public key and state. This addresses issues with the previous logic that might have incorrectly included or excluded transactions.
___
<tr>
<td>
<details>
<summary><strong>MarkAndListPendingTransactionsMutation.php</strong><dd><code>Refactor SQL Query for Transaction Filtering</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/GraphQL/Schemas/Primary/Mutations/MarkAndListPendingTransactionsMutation.php
<li>Refactored the SQL query to improve …

[PLA-1684] Fix sql query

---

src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchTransferBalanceMutation.php

enhancement
___
- Introduced a new method `getMethodName` in `BatchTransferBalanceMutation.php` to specify the serialization service method name, enhancing the mutation's clarity and maintainability.
___
<tr>
<td>
<details>
<summary><strong>BatchTransferBalanceMutation.php</strong><dd><code>Add Method to Get Serialization Service Method Name</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchTransferBalanceMutation.php
<li>Added a new method <code>getMethodName</code> to return the serialization service <br>method name 'Batch'.<br>
</details>
</td>
<td><a …

[Hotfix] Issue with BatchTransferBalance on Fuel-Tanks package

---

src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/FreezeStateMutated.php
src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/FuelTankCreated.php

___
- Corrected the data type of `isFrozen` from `string` to `bool` in `FreezeStateMutated` event, ensuring it defaults to `false`.
- Enhanced the parsing of `tankName` and `tankId` in `FuelTankCreated` event to ensure they are correctly prefixed.
___
<tr>
<td>
<details>
<summary><strong>FreezeStateMutated.php</strong><dd><code>Correct Type and Default for `isFrozen` in `FreezeStateMutated`</code></dd></summary>
<hr>
src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/FreezeStateMutated.php
<li>Changed the type of <code>$isFrozen</code> from <code>string</code> to <code>bool</code>.<br> <li> Ensured <code>$isFrozen</code> …

[PLA-1706] Fixes fuelTank event argument

---

src/Models/BaseModel.php
src/Models/Laravel/Attribute.php
src/Models/Laravel/Token.php

enhancement
___
- Added a new `modelOwner` attribute method to both `BaseModel` and `Token` model to return the owner's wallet ID.
- Enhanced `Attribute` model with a new `pivotIdentifier` method to generate a unique identifier, throwing an exception if no collection is found.
___
<tr>
<td>
<details>
<summary><strong>BaseModel.php</strong><dd><code>Add Model Owner Attribute to BaseModel</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Models/BaseModel.php
<li>Added <code>modelOwner</code> method to return the owner's wallet ID as an …

[PLA-1685] Add model owner attribute

---

src/Events/Substrate/MultiTokens/TokenReserved.php
src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionMutated.php

bug_fix, enhancement
___
- Refactored `CollectionMutated` class to use a more generic `Event` class instead of `PolkadartEvent`.
- Removed debugging statements and an unnecessary exception to clean up the code.
- Added a new exception throw for unimplemented royalty mutations, improving error handling.
- Simplified wallet ID retrieval by introducing a new method `firstOrStoreAccount`, enhancing code maintainability.
- Updated logging statements to provide more relevant information during the collection update process.
___
<tr>
<td>
<details>
<summary><strong>CollectionMutated.php</strong><dd><code>Refactor and Enhance Error Handling in CollectionMutated …

[PLA-1723][PLA-1724] Fixes CollectionMutated & TokenReserved websocket event

---

src/Enums/Substrate/MultiTokensEventType.php
src/Events/Substrate/MultiTokens/CollectionTransferred.php
src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/CollectionTransferred.php
src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionMutated.php
src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionTransferred.php

Enhancement
___
- Added support for a new event type `CollectionTransferred` across multiple classes to handle, broadcast, and process collection transfer events in the blockchain.
- Updated event type enumeration and processor methods to include the new event type.
- Implemented event broadcasting with detailed setup for channels and data handling.
- Added decoding functionality for the new event type from blockchain data.
- Enhanced event processing to update collection ownership and log changes.
___
<tr>
<td>
<details>
<summary><strong>MultiTokensEventType.php</strong><dd><code>Add CollectionTransferred Event Type and Processor …

[PLA-1729] Adds CollectionTransferred event

---

config/enjin-platform.php

enhancement
___
- This PR updates the `spec-version` in the Enjin platform configuration file to version 1006.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes
<tr>
<td>
<details>
<summary><strong>enjin-platform.php</strong><dd><code>Update spec-version in configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated the 'spec-version' environment variable from 1005 to 1006.
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/168/files#diff-e687a9c8af991f77587526ea6983e8c280929f8ccf6b989eb1eb83c0d8f4d220">+1/ …

Bump matrix to v1006

---

src/GraphQL/Schemas/Primary/Substrate/Queries/GetWalletsQuery.php

Bug fix
___
- Added `ResolvePage` middleware to `GetWalletsQuery` to resolve pagination issues.
- Included `ResolvePage` in the `use` statements to ensure proper middleware functionality.
___
<tr>
<td>
<details>
<summary><strong>GetWalletsQuery.php</strong><dd><code>Add ResolvePage middleware to GetWalletsQuery for pagination</code></dd></summary>
<hr>
src/GraphQL/Schemas/Primary/Substrate/Queries/GetWalletsQuery.php
<li>Added <code>ResolvePage</code> middleware to handle pagination.<br> <li> Included <code>ResolvePage</code> in the <code>use</code> statements.<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/173/files#diff-38b464 …

[PLA-1777] Resolve pagination issue

---

src/Package.php

Enhancement
___
- Added a new `getPath` method to retrieve the static path.
- Enhanced the `setPath` method to include an `overwrite` option, allowing conditional path setting.
- Introduced a `getPathToVendorFolder` method to dynamically determine the vendor folder path.
- Updated the `getAutoloader` method to use the new `getPathToVendorFolder` method for improved path handling.
___
<tr>
<td>
<details>
<summary><strong>Package.php</strong><dd><code>Enhance path handling and autoloader logic in Package class</code></dd></summary>
<hr>
src/Package.php
<li>Added <code>getPath</code> method to retrieve the static path.<br> <li> Modified <code>setPath</code> …

[PLA-1693] Improved local testing tweaks.

---

src/Services/Processor/Substrate/Codec/Decoder.php
src/Services/Processor/Substrate/Codec/Types/CollectionStorage.json
src/Services/Processor/Substrate/Codec/Types/TokenAccountsStorage.json
src/Services/Processor/Substrate/Codec/Types/TokenStorage.json
src/Services/Processor/Substrate/Parser.php
src/Support/helpers.php

Enhancement, Other
___
- Added support for new versioning in data decoding methods in `Decoder.php`.
- Introduced `getValue` method in both `Decoder.php` and `Parser.php` to retrieve values from nested arrays.
- Added `isRunningLatest` helper function to check for the latest network version.
- Updated JSON type definitions to include new structures for version 1010.
- Added TODO comments for future implementation of new fields in version 1010.
___
<tr>
<td>
<details>
<summary><strong>Decoder.php</strong><dd><code>Add support for new versioning in data decoding</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

[PLA-1873] Make sync work with both matrix versions

---

src/Services/Processor/Substrate/Codec/Encoder.php
src/Services/Processor/Substrate/Codec/Types/CreateFuelTank.json
src/Services/Processor/Substrate/Codec/Types/Dispatch.json
src/Services/Processor/Substrate/Codec/Types/DispatchAndTouch.json
src/Services/Processor/Substrate/Codec/Types/InsertRuleSet.json
src/Services/Processor/Substrate/Codec/Types/MutateFuelTank.json
src/Services/Processor/Substrate/Codec/Types/RemoveAccountRuleData.json
src/Services/Serialization/Implementations/Substrate.php
src/Services/Serialization/Interfaces/SerializationServiceInterface.php

Enhancement
___
- Added `encodeRaw` method to `Encoder` and `Substrate` classes for raw data encoding.
- Updated `SerializationServiceInterface` to include `encodeRaw` method.
- Added new types and structures for version 1010 in multiple JSON files, including `CreateFuelTankV1010`, `DispatchV1010`, `DispatchAndTouchV1010`, `InsertRuleSetV1010`, `MutateFuelTankV1010`, and `RemoveAccountRuleDataV1010`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>9 files</summary><table>
<tr>
<td>
<details>
<summary><strong>Encoder.php</strong><dd><code>Add `encodeRaw` method for raw data encoding</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

[PLA-1879] FT mutation support for v1010

---

src/Commands/TransactionChecker.php
src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/TokenMutated.php
src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenMutated.php

Enhancement, Bug fix
___
- Refactored block number calculation in `TransactionChecker` to use the last 100 synced blocks and added a network condition to the transaction query.
- Added new properties `anyoneCanInfuse` and `tokenName` in `TokenMutated` event class and updated the `fromChain` method to handle these properties.
- Renamed `behaviorMutation` to `behavior` in `TokenMutated` event class and updated related conditions and methods.
___
<tr>
<td>
<details>
<summary><strong>TransactionChecker.php</strong><dd><code>Refactor block number calculation and add network condition</code></dd></summary>
<hr>
src/Commands/TransactionChecker.php
<li>Refactored …

[PLA-1886] Improvement transaction-checker

---

src/Services/Processor/Substrate/BlockProcessor.php
src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ListingCreated.php

___
- Updated `spec-version` and `transaction-version` for `SUBSTRATE_CANARY` and `SUBSTRATE_CANARY_RELAY` in the configuration file.
- Refactored block processing methods in `BlockProcessor.php` to improve retry logic and remove redundant methods.
- Extended `overrideCallIndex` in `Encoder.php` with new entries for various `MultiTokens` and `Balances` methods.
- Fixed and enhanced the parsing logic in `ListingCreated.php` to handle new structure of listing data.
___
<tr>
<td>
<details>
<summary><strong>enjin-platform.php</strong><dd><code>Update spec and transaction versions in configuration</code>&nbsp; &nbsp; &nbsp; …

[PLA-1910] Fixes ListingCreated event

---

config/enjin-platform.php
src/Services/Blockchain/Implementations/Substrate.php
src/Services/Processor/Substrate/Codec/Encoder.php

Enhancement, Bug fix
___
- Updated `spec-version` to 1010 and `transaction-version` to 8 in `config/enjin-platform.php`.
- Added `mode` parameter to `createExtrinsic` method in `Substrate.php`.
- Extended `signingPayload` and `signingPayloadJSON` methods in `Encoder.php` to include `mode` and `metadataHash` parameters.
- Updated `addSignature` and `addFakeSignature` methods in `Encoder.php` to conditionally include `mode` based on `spec-version`.
___
<tr>
<td>
<details>
<summary><strong>enjin-platform.php</strong><dd><code>Update Substrate Canary configuration versions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

[PLA-1912] Add support for new signingPayload

---

src/Enums/Substrate/TransactionDeposit.php
src/GraphQL/Schemas/Primary/Traits/HasTransactionDeposit.php
tests/Unit/DepositFeeTest.php

Enhancement, Tests
___
- Added new deposit types `LISTING` and `FUEL_TANK` in `TransactionDeposit` enum.
- Updated `toGMP` method in `TransactionDeposit` to handle new deposit types.
- Extended `HasTransactionDeposit` trait to handle new mutations: `CreateListingMutation`, `CreateFuelTankMutation`, `AddAccountMutation`, and `BatchAddAccountMutation`.
- Introduced `getBatchAddFuelTankAccountDeposit` method to calculate deposits for batch account additions.
- Updated unit tests in `DepositFeeTest` to reflect new deposit values.
___
<tr>
<td>
<details>
<summary><strong>TransactionDeposit.php</strong><dd><code>Add new deposit types for listing and fuel …

[PLA-1927] Adds deposits for Marketplace and FuelTanks

---

config/enjin-platform.php
src/Enums/Substrate/TransactionDeposit.php
src/GraphQL/Schemas/Primary/Traits/HasTransactionDeposit.php
src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/CounterOfferAnswered.php
src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/CounterOfferPlaced.php
src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/CounterOfferRemoved.php
src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ExpiredListingRemoved.php
src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ListingConverted.php
src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ListingFilled.php
src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ProtocolFeeSet.php
src/Services/Processor/Substrate/Codec/Types/ListingStorage.json
tests/Unit/DepositFeeTest.php

Enhancement, Tests
___
- Updated Substrate Canary `spec-version` to 1011 and `transaction-version` to 9.
- Added new transaction deposit types `LISTING` and `FUEL_TANK`.
- Extended transaction deposit handling for new mutations in GraphQL schema.
- Added new event classes for `CounterOfferAnswered`, `CounterOfferPlaced`, `CounterOfferRemoved`, `ExpiredListingRemoved`, `ListingConverted`, and `ProtocolFeeSet`.
- Extended `ListingFilled` event with a new `price` field.
- Updated unit tests to reflect new deposit values.
- Updated `ListingStorage` types to support new offer state.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><details><summary>1 files</summary><table>
<tr>
<td>
<details> …

[PLA-1927] Marketplace v1011 changes

---

src/GraphQL/Types/Input/Substrate/TokenFilterInputType.php
src/GraphQL/Types/Substrate/WalletType.php
src/Models/Laravel/Traits/EagerLoadSelectFields.php
tests/Feature/GraphQL/Queries/GetWalletTest.php
tests/Feature/GraphQL/Resources/GetWallet.graphql

Enhancement, Tests
___
- Added a new `TokenFilterInputType` class to support bulk filtering of tokens.
- Enhanced the `WalletType` class by adding a `bulkFilter` field.
- Implemented bulk filtering logic in the `loadWallet` method of `EagerLoadSelectFields` trait.
- Added unit tests for the `bulkFilter` functionality in `GetWalletTest`.
- Updated the `GetWallet` GraphQL query to support `bulkFilter` argument.
___
<tr>
<td>
<details>
<summary><strong>TokenFilterInputType.php</strong><dd><code>Add TokenFilterInputType for bulk filtering tokens</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

[PLA-1930] Add bulk filter to GetWallet query

---

lang/en/type.php
src/GraphQL/Types/Scalars/IntegerRangeStringType.php

enhancement, documentation
___
- Implemented a new `IntegerRangeStringType` scalar class for GraphQL, which includes methods for serializing, parsing, and validating integer range strings.
- Added a description for the `integer_range` scalar in the language file to provide guidance on its usage.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>type.php</strong><dd><code>Add description for IntegerRangeString scalar in language file</code></dd></summary>
<hr>
lang/en/type.php
- Added a description for `integer_range` in the language file.
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/241/files#diff-0663ed15566d07f6c546968e73ffec6731719 …

[PLA-1984] Move IntegerRangeString scalar

---

src/Commands/RelayWatcher.php
src/Services/Processor/Substrate/DecoderService.php
src/Services/Processor/Substrate/Processor.php
src/Services/Processor/Substrate/State.php

enhancement
___
- Implemented dependency injection for `DecoderService` in `RelayWatcher`, `Processor`, and `DecoderService` classes to improve code modularity and testability.
- Added `setNetwork` method in `DecoderService` to allow dynamic network configuration.
- Refactored `State` class to use dependency injection for `Processor`, replacing direct instantiation.
___
<tr>
<td>
<details>
<summary><strong>RelayWatcher.php</strong><dd><code>Implement dependency injection for DecoderService</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Commands/RelayWatcher.php
<li>Removed direct instantiation of …

[PLA-2016] Use Dependency Injection for DecoderService

---

lang/en/error.php
src/GraphQL/Enums/TransactionMethodEnum.php
src/GraphQL/Schemas/Primary/Mutations/AddToTrackedMutation.php
src/GraphQL/Schemas/Primary/Mutations/RemoveFromTrackedMutation.php
src/Services/Database/CollectionService.php
src/Services/Database/SyncableService.php
src/Services/Processor/Substrate/Events/Implementations/MultiTokens/CollectionCreated.php
src/Services/Processor/Substrate/Events/SubstrateEvent.php

enhancement, bug_fix
___
- Introduced a new `SyncableService` class to manage syncable entities, providing methods for retrieval, insertion, and synchronization.
- Refactored `AddToTrackedMutation` to utilize `SyncableService` instead of directly interacting with the `Syncable` model.
- Integrated `SyncableService` into event processing classes, such as `CollectionCreated` and `SubstrateEvent`.
- Removed the `hotSync` method from `CollectionService` and moved its functionality to `SyncableService`.
- Enhanced `TransactionMethodEnum` by sorting mutation names before converting them to an array.
___
<tr>
<td>
<details> …

[PLA-2015] Improve syncable tracking.

---

src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/FuelTankMutated.php
src/Services/Processor/Substrate/Codec/Types/CreateFuelTank.json
src/Services/Processor/Substrate/Codec/Types/Dispatch.json
src/Services/Processor/Substrate/Codec/Types/DispatchAndTouch.json
src/Services/Processor/Substrate/Codec/Types/FuelTankAccountStorage.json
src/Services/Processor/Substrate/Codec/Types/InsertRuleSet.json
src/Services/Processor/Substrate/Codec/Types/MutateFuelTank.json
src/Services/Processor/Substrate/Codec/Types/TankStorage.json
src/Services/Processor/Substrate/Events/SubstrateEvent.php

enhancement
___
- Enhanced the `getValue` method in `SubstrateEvent.php` to support multiple key types and wrapped keys using `Arr::wrap`.
- Updated JSON structures in `CreateFuelTank.json`, `FuelTankAccountStorage.json`, and `TankStorage.json` to align with new FuelTanks v2.0.0 specifications.
- Removed deprecated structures and added new fields such as `CoveragePolicy` and `RequireSignature`.
___
<tr>
<td>
<details>
<summary><strong>SubstrateEvent.php</strong><dd><code>Enhance getValue method to support multiple key types</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Services/Processor/Substrate/Events/SubstrateEvent.php
<li>Updated …

[PLA-2038] Changes for supporting FuelTanks v2.0.0

---

config/enjin-platform.php
config/enjin-runtime.php
src/Services/Processor/Substrate/BlockProcessor.php
src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ListingRemovedUnderMinimum.php

Enhancement, Other
___
- Added a new event class `ListingRemovedUnderMinimum` to handle specific marketplace events.
- Updated the Canary network `spec-version` to 1013 in the configuration.
- Added a new `specVersion` 1013 entry in the runtime configuration with block number and hash.
- Fixed the calculation of time taken to ingest block headers in the `BlockProcessor`.
___
<tr>
<td>
<details>
<summary><strong>enjin-platform.php</strong><dd><code>Update Canary network spec-version to 1013</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

[PLA-2041] Adds ListingRemovedUnderMinimum & canary v1013 runtime

---

src/Enums/Substrate/MultiTokensEventType.php
src/Events/Substrate/MultiTokens/TokenInfused.php
src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/Infused.php
src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Infused.php
src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenMutated.php

enhancement
___
- Added support for the `Infused` event type in the `MultiTokensEventType` enum and its processing logic.
- Implemented the `TokenInfused` class to handle infused events and set up broadcasting channels.
- Defined the `Infused` class to parse and handle infused events from the blockchain.
- Added logic to update collection and token infusion values in the `Infused` class.
- Updated `TokenMutated` class to handle the `anyoneCanInfuse` attribute.
___
<tr>
<td>
<details>
<summary><strong>MultiTokensEventType.php</strong><dd><code>Add Infused event type to MultiTokensEventType enum</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

[PLA-2026] Add support for infused at ingest

---

src/Commands/SyncMetadata.php

enhancement
___
- Refactored the job dispatch logic in `SyncMetadata` by introducing a new method `dispatchSyncJob`.
- This change promotes code reuse and makes it easier to override the job dispatch logic if needed.
___
<tr>
<td>
<details>
<summary><strong>SyncMetadata.php</strong><dd><code>Refactor job dispatch logic into a separate method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Commands/SyncMetadata.php
<li>Introduced a new method <code>dispatchSyncJob</code> to encapsulate job dispatch <br>logic.<br> <li> Replaced direct job dispatch with a call to the new method.<br>
</details>
</td>
<td><a …

[PLA-2023] Make function for easy override

---

src/Services/Processor/Substrate/Codec/Polkadart/Extrinsics/MultiTokens/Mint.php
src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenCreated.php

enhancement, bug fix
___
- Updated the `Mint` class to modify token minting parameters, including `recipient`, `collection_id`, `token_id`, `initial_supply`, and `metadata`.
- Enhanced the `TokenCreated` class by adding logging functionality and improving token creation logic.
- Removed unnecessary calculations for `unitPrice` and `minBalance`.
- Implemented conversion for `name` and `symbol` metadata using `HexConverter`.
___
<tr>
<td>
<details>
<summary><strong>Mint.php</strong><dd><code>Update token minting parameters and metadata handling</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

[PLA-2026] Get new fields from Extrinsic for CreateToken

---

src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchMintMutation.php

enhancement
___
- Simplified the encoding logic in the `BatchMintMutation` class by removing the `MintParams` type check.
- Enhanced the lambda function for encoding recipient data, making it more concise and efficient.
- Removed unnecessary conditional logic related to appending data, streamlining the code.
___
<tr>
<td>
<details>
<summary><strong>BatchMintMutation.php</strong><dd><code>Simplify and enhance batch mint encoding logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchMintMutation.php
<li>Removed the <code>MintParams</code> type check …

[PLA-2054] Fix batch mint utility

---

src/GraphQL/Types/Substrate/CollectionType.php
src/GraphQL/Types/Substrate/WalletType.php
src/Models/Laravel/Traits/EagerLoadSelectFields.php
tests/Feature/GraphQL/Mutations/ApproveTokenTest.php
tests/Feature/GraphQL/Queries/GetWalletTest.php
tests/Feature/GraphQL/Resources/GetWallet.graphql

enhancement
___
- Enhanced filtering capabilities by adding new arguments and validation rules to GraphQL types.
- Introduced `tokenIds` argument in `CollectionType` for filtering tokens.
- Added `walletAccounts` argument in `WalletType` for filtering account approvals.
- Improved filtering logic in `EagerLoadSelectFields` trait for token and account approvals.
___
<tr>
<td>
<details>
<summary><strong>CollectionType.php</strong><dd><code>Add tokenIds argument to tokens field</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

[PLA-2090] Add filters to subqueries

---

src/GraphQL/Types/Scalars/Traits/HasIntegerRanges.php

Enhancement
___
- Added a helper function `isIntegerRange` to check for range format.
- Enhanced the `HasIntegerRanges` trait with new functionality.
___
<tr>
<td>
<details>
<summary><strong>HasIntegerRanges.php</strong><dd><code>Added `isIntegerRange` method to check range format</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/GraphQL/Types/Scalars/Traits/HasIntegerRanges.php
<li>Added a new method <code>isIntegerRange</code>.<br> <li> The method checks if a string contains a range format (<code>..</code>).
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/310/files#diff-598969d2f38dd3b6377c66c2a3d7baf97eb6 …

[PLA-2125] Add helper function

---

src/GraphQL/Schemas/Primary/Substrate/Queries/GetTokenQuery.php
src/Rules/TokenEncodeExists.php
tests/Feature/GraphQL/Queries/GetTokenTest.php

Bug fix, Tests
___
- Enhanced validation logic for token existence checks.
- Added support for `collectionId` in token validation.
- Updated test cases to cover new validation scenarios.
- Improved error handling for invalid token inputs.
___
<tr>
<td>
<details>
<summary><strong>TokenEncodeExists.php</strong><dd><code>Enhance token validation with collectionId support</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Rules/TokenEncodeExists.php
<li>Added <code>collectionId</code> support in token validation logic.<br> <li> Used <code>Arr::get</code> to retrieve <code>collectionId</code> with a default value.<br> <li> Enhanced …

[PLA-2127] Fix validation for token exist

---

src/GraphQL/Types/Scalars/Traits/HasIntegerRanges.php

___
- Fixed incorrect usage of helper method in static context.
- Introduced `$self` variable to handle instance methods in static function.
- Improved range serialization logic with initialization of `$curRange`.
- Refactored code for better readability and maintainability.
___
<tr>
<td>
<details>
<summary><strong>HasIntegerRanges.php</strong><dd><code>Fix and refactor integer range handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/GraphQL/Types/Scalars/Traits/HasIntegerRanges.php
<li>Added <code>$self</code> variable to …

[PLA-2125] Fix calling helper in static function

---

src/GraphQL/Types/Scalars/Traits/HasIntegerRanges.php
tests/Feature/Controllers/QrControllerTest.php
tests/Feature/GraphQL/Mutations/ApproveTokenTest.php
tests/Feature/GraphQL/Mutations/BatchTransferTest.php
tests/Feature/GraphQL/Mutations/OperatorTransferTokenTest.php
tests/Feature/GraphQL/Mutations/RemoveAllAttributesTest.php
tests/Feature/GraphQL/Mutations/RemoveTokenAttributeTest.php
tests/Feature/GraphQL/Mutations/SimpleTransferTokenTest.php
tests/Feature/GraphQL/Mutations/UnapproveTokenTest.php

Enhancement
___
- Refactored `expandRanges` function to be non-static.
- Adjusted method signature for better encapsulation.
___
<tr>
<td>
<details>
<summary><strong>HasIntegerRanges.php</strong><dd><code>Refactor `expandRanges` method to non-static</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/GraphQL/Types/Scalars/Traits/HasIntegerRanges.php
<li>Changed <code>expandRanges</code> method from static to non-static.<br> <li> Updated method signature to reflect the change.
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/313/files#diff-598969d2f38dd3b6377c66c2 …

[PLA-2125] Refactor expandRanges function

---

config/enjin-platform.php
config/enjin-runtime.php

Enhancement
___
- Updated `spec-version` to 1014 in `enjin-platform` configuration.
- Added new runtime entry for `specVersion` 1014 in `enjin-runtime`.
- Ensured compatibility with the latest blockchain metadata.
___
<tr>
<td>
<details>
<summary><strong>enjin-platform.php</strong><dd><code>Update `spec-version` to 1014 in platform configuration</code>&nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated the <code>spec-version</code> value from 1012 to 1014.<br> <li> Ensures compatibility with the latest blockchain metadata.
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/314/files#diff-e687a9c8af991f77587526ea6 …

[PLA-2128] Adds new metadata v1014

---

composer.json
config/enjin-platform.php
src/Enums/Global/PlatformCache.php
src/Enums/Substrate/SystemEventType.php
src/Events/Substrate/System/CodeUpdated.php
src/Services/Blockchain/Implementations/Substrate.php
src/Services/Processor/Substrate/BlockProcessor.php
src/Services/Processor/Substrate/Codec/Polkadart/Events/System/CodeUpdated.php
src/Services/Processor/Substrate/DecoderService.php
src/Services/Processor/Substrate/Events/Implementations/System/CodeUpdated.php
src/Services/Processor/Substrate/State.php
src/Support/Util.php
src/Support/helpers.php
tests/TestCase.php

Enhancement, Bug fix
___
- Removed hardcoded `spec-version` and `transaction-version` configurations, replacing them with dynamic runtime updates.
- Introduced a new `CodeUpdated` event to handle runtime updates and cache invalidation.
- Enhanced caching mechanisms for runtime configurations using `cachedRuntimeConfig`.
- Added new utility functions and refactored existing ones for better runtime version handling.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><details><summary>1 files</summary><table>
<tr>
<td><strong>enjin-platform.php</strong><dd><code>Removed hardcoded runtime configurations and updated node URLs.</code></dd></td>
<td><a …

[PLA-1761] Runtime upgrade
