enjin/platform-core

src/CoreServiceProvider.php
To avoid unexpected issues it is recommended to run scheduled commands from within the app implementing this package, using the `schedule()` method in the `Kernel` class: https://laravel.com/docs/10.x/scheduling or via other similar means of running command on a cron.
=> [PLA-1422] Remove scheduled command from CoreServiceProvider.

src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchMintMutation.php, src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchTransferMutation.php, tests/Feature/GraphQL/Mutations/BatchMintTest.php, tests/Feature/GraphQL/Mutations/BatchTransferTest.php, tests/Unit/EncodingTest.php
___
- Added support for `continueOnFailure` in both batch mint and batch transfer mutations, allowing transactions to continue even if some fail.
- Introduced new test cases to verify the functionality of `continueOnFailure` for both batch minting and transferring.
- Updated and added encoding tests to ensure proper handling of utility batches, including scenarios with `continueOnFailure`.
___
<tr>
<td>
<details>
<summary><strong>BatchMintMutation.php</strong><dd><code>Add continueOnFailure Support to Batch Mint Mutation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> [PLA-1590] Add support for batch transactions with continueOnFailure.

config/enjin-platform.php, database/factories/BlockFactory.php, src/Models/Laravel/Block.php, tests/Feature/Commands/PruneTest.php
___
- Added a new configuration option `prune_blocks` to specify the number of days to retain block data before pruning.
- Updated the Block model to support mass pruning based on the new configuration.
- Updated the BlockFactory to use a more flexible number generation for block numbers.
- Added tests to verify the functionality of pruning blocks based on the new configuration.
___
<tr>
<td>
<details>
<summary><strong>enjin-platform.php</strong><dd><code>Add Configuration for Pruning Blocks</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Add mass pruneable blocks

src/GraphQL/Types/Substrate/AttributeType.php, src/Models/Laravel/Block.php, src/Models/Laravel/Token.php, tests/Feature/GraphQL/Queries/GetTokenTest.php
enhancement
___
- Enhanced URI attribute resolution in `AttributeType.php` to include both `collection_chain_id` and `token_chain_id`.
- Updated documentation for the return type of the prunable method in `Block.php`.
- Introduced a new mechanism in `Token.php` for fetching metadata using the collection's URI attribute as a fallback when token's metadata is not directly available.
- Updated `GetTokenTest.php` to assert the new format of URI values that include both collection and token chain IDs.
___
<tr>
<td>
<details>
<summary><strong>AttributeType.php</strong><dd><code>Enhanced URI Attribute Resolution with Collection ID Support</code></dd></summary> …
=> [PLA-1608] Token metadata fallback, and {id} replacement.

config/enjin-platform.php
enhancement
___
- Updated `spec-version` and `transaction-version` in the `enjin-platform.php` configuration file.
- Changes apply to both `enjin` and `canary` configurations, ensuring compatibility with new blockchain specifications.
___
<tr>
<td>
<details>
<summary><strong>enjin-platform.php</strong><dd><code>Update Spec and Transaction Versions for Enjin and Canary</code></dd></summary>
<hr>
<li>Updated <code>spec-version</code> from 1003 to 1005 for both <code>enjin</code> and <code>canary</code> <br>configurations.<br> <li> Updated <code>transaction-version</code> from 5 to 7 for both <code>enjin</code> and …
=> [PLA-1681] Bump transactionVersion and specVersion

src/Events/Substrate/Balances/Transfer.php
enhancement
___
- Added the transaction hash to the event broadcast data in `Transfer.php`, enhancing the data's richness and traceability.
___
<tr>
<td>
<details>
<summary><strong>Transfer.php</strong><dd><code>Add Transaction Hash to Broadcast Data</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Events/Substrate/Balances/Transfer.php
<li>Added 'transactionHash' to the broadcast data array, using the <br>'transaction_chain_hash' property from the transaction model.<br>
</details>
</td>
<td><a …
=> [PLA-1690] Add transaction hash to event data

src/Services/Processor/Substrate/Codec/Types/CreateFuelTank.json, src/Services/Processor/Substrate/Codec/Types/TankStorage.json
enhancement
___
- Added "WhitelistedPallets" to the TankStorage codec to support new storage and dispatch rule types.
___
<tr>
<td>
<details>
<summary><strong>TankStorage.json</strong><dd><code>Add WhitelistedPallets to TankStorage Codec</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Services/Processor/Substrate/Codec/Types/TankStorage.json
<li>Added "WhitelistedPallets" to the list of Storage types.<br> <li> Included "WhitelistedPallets" with type "Vec<Bytes>" in DispatchRuleStorage <br>enum.<br>
</details>
</td>
<td><a …
=> [PLA-1704] Add WhitelistedPallets codec

src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/AuctionFinalized.php, src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/BidPlaced.php, src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ListingCancelled.php, src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ListingCreated.php, src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/ListingFilled.php
enhancement
___
- Standardized the conversion of listing IDs across various marketplace event classes to ensure consistency and reduce code duplication.
- Changed the `salt` property in the ListingCreated event from an array to a hex-prefixed string to align with data type expectations.
___
<tr>
<td>
<details>
<summary><strong>AuctionFinalized.php</strong><dd><code>Refactor Listing ID Conversion in AuctionFinalized Event</code>&nbsp; </dd></summary>
<hr>
src/Services/Processor/Substrate/Codec/Polkadart/Events/Marketplace/AuctionFinalized.php
<li>Refactored listing ID conversion to use <code>HexConverter::prefix</code> method <br>uniformly.<br>
</details> …
=> [PLA-1706] Decoder changes for marketplace

src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenCreated.php
Enhancement
___
- Added handling for `force_mint` in the token creation event parsing logic alongside existing `mint` handling.
- This update allows the system to recognize and process `force_mint` actions as part of the token creation events.
- Modified the parameter extraction logic to include a fallback to `CreateOrMint` when `CreateToken` is not specified.
___
<tr>
<td>
<details>
<summary><strong>TokenCreated.php</strong><dd><code>Support for `force_mint` in Token Creation Event Parsing</code>&nbsp; </dd></summary>
<hr>
src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenCreated.php
<li>Added support for <code>force_mint</code> …
=> [PLA-1720] Support for force_mint.

src/Commands/Sync.php, src/Commands/contexts/get_storage.php
bug_fix
___
- Implemented a retry mechanism in `get_storage.php` to handle exceptions during RPC requests.
- The system will now continue to retry the `state_getKeysPaged` RPC request if an exception occurs, enhancing robustness.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Error handling
<tr>
<td>
<details>
<summary><strong>get_storage.php</strong><dd><code>Implement Retry Mechanism for RPC Requests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Commands/contexts/get_storage.php
<li>Added a try-catch block around the RPC request to handle exceptions <br>and retry.<br> <li> The loop will continue retrying the request …
=> [PLA-1721] Retry RPC request on sync

src/Events/Substrate/MultiTokens/TokenUnreserved.php
bug_fix, enhancement
___
- Updated the `TokenUnreserved` event handling by replacing `HexConverter` with `PalletIdentifier` for reserve ID conversion.
- This change improves the clarity and correctness of reserve ID handling by utilizing a more specific and reliable enum.
___
<tr>
<td>
<details>
<summary><strong>TokenUnreserved.php</strong><dd><code>Enhance Reserve ID Handling in TokenUnreserved Event</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Events/Substrate/MultiTokens/TokenUnreserved.php
<li>Removed usage of <code>HexConverter</code> for converting reserve IDs.<br> <li> Added usage of <code>PalletIdentifier</code> enum to handle …
=> [PLA-1726] Fixes TokenUnreserved websocket event

src/Http/Controllers/GraphQLController.php
bug_fix
___
- Added logic in `GraphQLController` to check if the GraphQL response contains errors.
- If errors are found, the HTTP status code is set to 400, indicating a client-side error.
___
<tr>
<td>
<details>
<summary><strong>GraphQLController.php</strong><dd><code>Handle GraphQL Errors with HTTP 400 Status Code</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Http/Controllers/GraphQLController.php
<li>Added a check for 'errors' in the GraphQL response.<br> <li> Set HTTP status code to 400 if errors are present.<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/159/files#diff …
=> [PLA-1739] Return a 400 status code if the GraphQL response contains errors.

config/enjin-platform.php, src/CoreServiceProvider.php, src/Models/Laravel/PendingEvent.php, tests/Feature/Commands/PruneTest.php
bug_fix, tests
___
- Corrected the logic in `PendingEvent::prunable()` to properly check for events that are past the expiration date.
- Added a new test to verify that events sent today are not pruned, ensuring that only truly expired events are affected.
___
<tr>
<td>
<details>
<summary><strong>PendingEvent.php</strong><dd><code>Fix Prunable Method in PendingEvent Model</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Models/Laravel/PendingEvent.php
<li>Changed the condition to correctly identify prunable events based on <br>the 'sent' date.
</details>
</td>
<td><a …
=> [PLA-1747] Fix prune pending event

src/Clients/Abstracts/HttpAbstract.php, src/Services/Processor/Substrate/BlockProcessor.php
enhancement
___
- Added retry mechanism to HTTP client configuration in `HttpAbstract.php` to enhance reliability.
- Implemented retry logic in `BlockProcessor.php` for fetching events and extrinsics, improving data fetching robustness.
___
<tr>
<td>
<details>
<summary><strong>HttpAbstract.php</strong><dd><code>Enhance HTTP Client with Retry Mechanism</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Clients/Abstracts/HttpAbstract.php
- Added retry logic to the HTTP client configuration.
</details>
</td>
<td><a …
=> [PLA-1751] Add retries for decoder

config/enjin-platform.php
enhancement
___
- Updated the `spec-version` for the Matrix Canary environment in the configuration file to reflect the new version 1006.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes
<tr>
<td>
<details>
<summary><strong>enjin-platform.php</strong><dd><code>Update Matrix Canary specVersion in Configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated the <code>spec-version</code> for the Matrix Canary configuration from 1005 <br>to 1006.<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/165/files#diff-e687a9c8af991f77587526ea6983e8c280929f8ccf6b989eb1eb83c0d8f4d220">+1/-1</a>&nbsp; …
=> [PLA-1754] Change specVersion for Matrix Canary

src/GraphQL/Schemas/Primary/Substrate/Mutations/BurnMutation.php, tests/Feature/GraphQL/Mutations/BurnTest.php
Bug fix, Enhancement, Tests
___
- Refactored the `BurnMutation` to improve clarity and correctness in handling the `removeTokenStorage` parameter.
- Updated validation logic in `BurnMutation` to conditionally check collection ownership based on `removeTokenStorage`.
- Enhanced test coverage in `BurnTest` to include new scenarios testing the `removeTokenStorage` functionality.
- Added specific test cases to handle token burning permissions and validations under different conditions.
___
<tr>
<td>
<details>
<summary><strong>BurnMutation.php</strong><dd><code>Refactor and Enhance Validation in BurnMutation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> [PLA-1755] Fixes burn mutation validation

src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/FuelTankCreated.php
bug_fix
___
- Fixed the method used for converting the tank name from hexadecimal to string in `FuelTankCreated.php`. This ensures the tank name is correctly interpreted and displayed.
___
<tr>
<td>
<details>
<summary><strong>FuelTankCreated.php</strong><dd><code>Fix Hex Conversion for Tank Name in FuelTankCreated</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Services/Processor/Substrate/Codec/Polkadart/Events/FuelTanks/FuelTankCreated.php
- Changed method for converting tank name from hex to string.
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/167/files#diff-7e705dde29a65acb39b82223d7385de1ac8ad2dbc0b587 …
=> [PLA-1757] Fixes hex FuelTanks name

lang/en/validation.php, src/GraphQL/Schemas/Primary/Substrate/Mutations/SetCollectionAttributeMutation.php, src/GraphQL/Schemas/Primary/Substrate/Mutations/SetTokenAttributeMutation.php, src/GraphQL/Types/Input/Substrate/AttributeInputType.php, src/Rules/StringMaxByteLength.php, tests/Feature/GraphQL/Mutations/CreateCollectionTest.php, tests/Feature/GraphQL/Mutations/SetCollectionAttributeTest.php, tests/Feature/GraphQL/Mutations/SetTokenAttributeTest.php
___
- Introduced a new validation rule `StringMaxByteLength` to enforce maximum byte lengths on string attributes.
- Updated attribute validation rules in various mutations to use the new `StringMaxByteLength` rule.
- Added validation error messages for exceeding string size limits.
- Enhanced test coverage to verify the new validation behavior on attribute length constraints.
___
<tr>
<td>
<details>
<summary><strong>validation.php</strong><dd><code>Add new validation message for string size</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> [PLA-1767] Increases attribute validation size

src/Commands/RelayWatcher.php
Enhancement
___
- Added the `TransactionCreated` event broadcast to the `createDaemonTransaction` method in `RelayWatcher.php` to enhance transaction handling.
- Imported the necessary `TransactionCreated` class to enable event broadcasting.
- Stored the result of `Transaction::create` in a variable to use for event broadcasting.
___
<tr>
<td>
<details>
<summary><strong>RelayWatcher.php</strong><dd><code>Implement Transaction Created Event Broadcast in RelayWatcher</code></dd></summary>
<hr>
src/Commands/RelayWatcher.php
<li>Added import for <code>TransactionCreated</code> event.<br> <li> Modified <code>createDaemonTransaction</code> to store the created …
=> [PLA-1769] Fire transaction created event on relay watcher

src/Commands/RelayWatcher.php, src/Enums/Substrate/XcmOutcome.php, src/Events/Substrate/Balances/Teleport.php, src/GraphQL/Enums/TransactionMethodEnum.php, src/Services/Processor/Substrate/Codec/Polkadart/Events/XcmPallet/Attempted.php
enhancement, bug_fix
___
- Introduced new event handling for `Teleport` transactions and outcomes using the `XcmOutcome` enum.
- Enhanced transaction update logic in `RelayWatcher.php` to improve accuracy of transaction state updates.
- Added new enum `XcmOutcome` and a new event class `Teleport` to handle specific substrate balance operations.
- Updated GraphQL enum to include new transaction method `LimitedTeleportAssets`.
- Implemented new event class `Attempted` to process specific events from the XcmPallet.
___
<tr>
<td>
<details>
<summary><strong>RelayWatcher.php</strong><dd><code>Enhance transaction handling and add new event …
=> [PLA-1770] Adds Balances.Teleport + LimitedTeleportAssets method.

src/Commands/Sync.php
enhancement
___
- Updated the condition in the `getKeys` method to check the `config('enjin-platform.sync.all')` setting instead of whether `collectionFilter` is empty.
___
<tr>
<td>
<details>
<summary><strong>Sync.php</strong><dd><code>Update condition to use configuration setting for sync</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Commands/Sync.php
<li>Modified the condition to check <code>config('enjin-platform.sync.all')</code> <br>instead of <code>empty($collectionFilter)</code>.<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/175/files#diff-9b0a60cf1d209941117e6dc62d39f195a8fb08d7e6510e532321c5ee01c6f66b">+1/-1 …
=> [Hotfix] Fixes platform:sync on SYNC_ALL

src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Minted.php
Bug fix
___
- Fixed an issue in `Minted.php` where the wrong variable was used to update the token supply.
___
<tr>
<td>
<details>
<summary><strong>Minted.php</strong><dd><code>Fix incorrect variable in token supply update.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Services/Processor/Substrate/Events/Implementations/MultiTokens/Minted.php
- Corrected variable used in updating token supply.
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/177/files#diff-0689f287583f607993f60089eec05b58ecc23476db6c6a88c81b0db3f593048e">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
=> [PLA-1806] Fixes wrong var

src/Services/Database/TokenService.php, src/Services/Processor/Substrate/Events/Implementations/MultiTokens/AttributeSet.php
Bug fix
___
- Added `HexConverter` to convert and prefix attribute keys and values in `TokenService` and `AttributeSet` event.
- Ensured attribute keys are converted to hex in the `attributeExistsInToken` validation rule.
- Ensured attribute keys and values are prefixed when added via the `AttributeSet` substrate event.
___
<tr>
<td>
<details>
<summary><strong>TokenService.php</strong><dd><code>Convert attribute keys to hex in TokenService.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Services/Database/TokenService.php
<li>Added <code>HexConverter</code> usage to convert attribute keys to hex …
=> [PLA-1855] Fixes for hex encoded attribute keys and values.

src/Services/Processor/Substrate/ExtrinsicProcessor.php
Bug fix
___
- Removed the special handling for `FuelTankCreated` event parameters in the `saveExtrinsicEvents` method.
- Simplified the parameter processing by directly using the `$event->getParams()` method.
___
<tr>
<td>
<details>
<summary><strong>ExtrinsicProcessor.php</strong><dd><code>Simplify event parameter processing in `saveExtrinsicEvents` method.</code></dd></summary>
<hr>
src/Services/Processor/Substrate/ExtrinsicProcessor.php
<li>Removed special handling for <code>FuelTankCreated</code> event parameters.<br> <li> Simplified parameter processing by directly using <code>$event->getParams()</code>.<br> <br>
</details>
</td>
<td><a …
=> [PLA-1851] Fixes FuelTank events

src/GraphQL/Schemas/Primary/Substrate/Mutations/FreezeMutation.php, src/Models/Substrate/FreezeTypeParams.php, tests/Feature/GraphQL/Mutations/FreezeTest.php, tests/Unit/EncodingTest.php
Bug fix, Tests
___
- Fixed the issue where `freezeState` could be null by setting a default value of `FreezeStateType::TEMPORARY->value` in `FreezeTypeParams`.
- Removed an unused import `HexConverter` from `ExtrinsicProcessor`.
- Renamed a test method to `test_can_freeze_a_token_without_freeze_state` to reflect the test's purpose more accurately.
___
<tr>
<td>
<details>
<summary><strong>FreezeTypeParams.php</strong><dd><code>Fix token freeze with nullable <code>freezeState</code> by setting default value.</code></dd></summary>
<hr>
src/Models/Substrate/FreezeTypeParams.php
<li>Updated <code>freezeState</code> to default to …
=> [PLA-1838] Fixes token freeze with nullable freezeState

src/Rules/IsCollectionOwner.php, src/Rules/IsCollectionOwnerOrApproved.php, src/Support/Account.php
Enhancement, Bug fix
___
- Updated the collection owner validation logic by replacing `SS58Address::isSameAddress` with `Account::isAccountOwner`.
- Added a new static property `$walletAccounts` in the `Account` class.
- Introduced a new method `isAccountOwner` in the `Account` class to check if an account is the owner.
___
<tr>
<td>
<details>
<summary><strong>IsCollectionOwner.php</strong><dd><code>Update collection owner validation logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Rules/IsCollectionOwner.php
<li>Replaced …
=> [PLA-1837] Add account owner validation

composer.json, src/Services/Processor/Substrate/Codec/Types/CreateListing.json
enhancement
___
- Downgraded `rector/rector` dependency from version 1.2 to 1.0 in `composer.json`.
- Added new types `CreateListingV1010`, `ListingDataV1010`, and `OfferData` in `CreateListing.json` to support marketplace mutations.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>composer.json</strong><dd><code>Downgrade `rector/rector` dependency version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
composer.json
- Downgraded `rector/rector` dependency from version 1.2 to 1.0.
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/198/files#diff-d2ab9925cad7eac58e0ff4cc0 …
=> [PLA-1878] Marketplace mutations support to v1010

src/Commands/RelayWatcher.php, src/Events/Substrate/Balances/Teleport.php
___
- Updated `Teleport::safeBroadcast` method call in `RelayWatcher` to use an associative array for parameters.
- Refactored `Teleport` class constructor to accept a mixed type `event` parameter and updated its properties accordingly.
___
<tr>
<td>
<details>
<summary><strong>RelayWatcher.php</strong><dd><code>Update Teleport::safeBroadcast call with associative array</code></dd></summary>
<hr>
src/Commands/RelayWatcher.php
<li>Modified the <code>Teleport::safeBroadcast</code> method call to use an associative <br>array for parameters.<br> <li> Updated the parameters passed to <code>Teleport::safeBroadcast</code> to include …
=> [PLA-1885] Relay-watcher changes

src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/TokenMutated.php
Bug fix
___
- Fixed the condition for setting `tokenName` in the `TokenMutated` class to correctly handle array values.
___
<tr>
<td>
<details>
<summary><strong>TokenMutated.php</strong><dd><code>Fix condition for setting `tokenName` in `TokenMutated`</code>&nbsp; &nbsp; </dd></summary>
<hr>
src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/TokenMutated.php
<li>Fixed the condition for setting <code>tokenName</code> to correctly handle array <br>values.<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/206/files#diff-714b6f75ac7534170fca96927b2332ae1ac16f66104fa1350e088aa610d7ed90">+1/-1</a>&nbsp; &nbsp; &nbsp; …
=> [Hotfix] Fixes tokenMutated

src/GraphQL/Schemas/Primary/Substrate/Queries/GetTokensQuery.php, src/Models/Laravel/Token.php, src/Models/Laravel/Traits/EagerLoadSelectFields.php, tests/Feature/GraphQL/Queries/GetTokensTest.php
___
- Fixed cursor pagination issue by using a concatenated identifier in `GetTokensQuery`.
- Ensured `attributes` relation is loaded before accessing it in the `Token` model.
- Enhanced relation loading logic in `EagerLoadSelectFields` trait to include `collection` when `metadata` is present and avoid duplicates.
___
<tr>
<td>
<details>
<summary><strong>GetTokensQuery.php</strong><dd><code>Fix cursor pagination and add concatenated identifier</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/GraphQL/Schemas/Primary/Substrate/Queries/GetTokensQuery.php
<li>Added <code>DB</code> facade for raw SQL queries.<br> <li> Modified cursor …
=> [PLA-1904] Fix GetTokens query pagination

src/Services/Processor/Substrate/Codec/Encoder.php, tests/Unit/EncodingTest.php
Bug fix
___
- Fixed the `set_attribute` call index in the `Encoder` class by adding it to the `$overrideCallIndex` array with appropriate values.
___
<tr>
<td>
<details>
<summary><strong>Encoder.php</strong><dd><code>Fix `set_attribute` call index in Encoder class</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Services/Processor/Substrate/Codec/Encoder.php
<li>Added <code>MultiTokens.set_attribute</code> to the <code>$overrideCallIndex</code> array with <br>values [40, 9].<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/208/files#diff-9cf4c9f5fbba52860e055d9fd9d792ee1341497b928 …
=> [PLA-1897] Fix setAttribute callIndex

src/Events/Substrate/Balances/Teleport.php
Bug fix
___
- Modified the `Teleport` event constructor to include `from`, `to`, `amount`, and `destination` parameters.
- Changed `from` and `to` properties from `address` to `public_key` in the broadcast data and channels.
___
<tr>
<td>
<details>
<summary><strong>Teleport.php</strong><dd><code>Fix and update Teleport event constructor and properties</code>&nbsp; </dd></summary>
<hr>
src/Events/Substrate/Balances/Teleport.php
<li>Modified constructor parameters to include <code>from</code>, <code>to</code>, <code>amount</code>, and <br><code>destination</code>.<br> <li> Changed <code>from</code> and <code>to</code> properties from <code>address</code> to …
=> [PLA-1914] Fixes teleport event

src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchMintMutation.php, src/Models/Substrate/MintParams.php
Bug fix
___
- Added import for `MintParams` in `BatchMintMutation.php`.
- Added a condition to check if `params` is an instance of `MintParams` in `BatchMintMutation.php`.
- Added `depositor` field to the `toEncodable` method in `MintParams.php`.
___
<tr>
<td>
<details>
<summary><strong>BatchMintMutation.php</strong><dd><code>Fix and enhance minting logic in BatchMintMutation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/GraphQL/Schemas/Primary/Substrate/Mutations/BatchMintMutation.php
<li>Added import for <code>MintParams</code>.<br> <li> Added condition to check if <code>params</code> is an instance of …
=> [PLA-1915] Fixes MintParams

src/Support/Account.php
Bug fix
___
- Added `Arr` import from `Illuminate\Support` to `Account.php`.
- Wrapped `static::$walletAccounts` with `Arr::wrap` to ensure it is always treated as an array.
___
<tr>
<td>
<details>
<summary><strong>Account.php</strong><dd><code>Ensure `static::$walletAccounts` is always an array</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Support/Account.php
<li>Added <code>Arr</code> import from <code>Illuminate\Support</code><br> <li> Wrapped <code>static::$walletAccounts</code> with <code>Arr::wrap</code> to ensure it is an <br>array<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/217/files#diff-dd9 …
=> [PLA-1919] Make sure data is an array

src/Support/helpers.php
Bug fix
___
- Fixed the `isRunningLatest` function to correctly determine if the network is running the latest version by checking if the `spec-version` is greater than or equal to 1010.
___
<tr>
<td>
<details>
<summary><strong>helpers.php</strong><dd><code>Fix version check logic in `isRunningLatest` function</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Support/helpers.php
<li>Modified the <code>isRunningLatest</code> function to check if the <code>spec-version</code> is <br>greater than or equal to 1010 instead of strictly equal.<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/222/files#diff-3e5775295c528f7b783a114 …
=> [PLA-1931] Fix checking for running latest version

src/GraphQL/Schemas/Primary/Substrate/Mutations/RetryTransactionsMutation.php
enhancement
___
- Enhanced the `RetryTransactionsMutation` to use Laravel's `DB::transaction` for safer database operations.
- Updated the logic to conditionally remove the wallet public key if it matches the daemon's public key.
- Changed the import path for the `Transaction` model to align with Laravel's structure.
- Improved transaction update logic by iterating over each transaction and applying updates.
___
<tr>
<td>
<details>
<summary><strong>RetryTransactionsMutation.php</strong><dd><code>Enhance transaction retry logic with conditional public key removal</code></dd></summary>
<hr>
src/GraphQL/Schemas/Primary/Substrate/Mutations/RetryTransactionsMut …
=> [PLA-1956] Updates RetryTransaction to remove public key if equal to wallet daemon

database/migrations/2024_08_27_083621_add_network_to_pending_events_table.php, lang/en/query.php, lang/en/type.php, src/CoreServiceProvider.php, src/Events/PlatformBroadcastEvent.php, src/GraphQL/Schemas/Primary/Queries/GetPendingEventsQuery.php, src/GraphQL/Types/Global/PendingEventType.php, src/Models/Laravel/PendingEvent.php, tests/Feature/GraphQL/Queries/GetPendingEventsTest.php
___
- Added a `network` column to the `pending_events` table through a new migration.
- Enhanced the `GetPendingEventsQuery` to support filtering by event `names`.
- Updated the `PendingEvent` model and related GraphQL types to include the `network` field.
- Added a new test to ensure the `names` filter works correctly in fetching pending events.
- Updated language files to include descriptions for the new `network` field and `names` argument.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>6 files</summary><table>
<tr>
<td>
<details>
<summary><strong>2024_08_27_083621_add_network_to_pending_events_table.php</strong><dd><code>Add `network` column to `pending_events` …
=> [PLA-1966] Add network to GetPendingEvents

src/GraphQL/Schemas/Primary/Substrate/Queries/GetTokensQuery.php
Bug fix
___
- Fixed a bug in the SQL query by adding table names to the `CONCAT` function in the `GetTokensQuery` class.
- Ensured that `collection_id` and `id` are correctly referenced with the `tokens` table name to avoid ambiguity.
___
<tr>
<td>
<details>
<summary><strong>GetTokensQuery.php</strong><dd><code>Add table name to SQL select statement for identifier</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/GraphQL/Schemas/Primary/Substrate/Queries/GetTokensQuery.php
<li>Modified the SQL query to include table names in the <code>CONCAT</code> function.<br> <li> Ensured that <code>collection_id</code> and <code>id</code> are prefixed with …
=> [PLA-1948] Add table name to select.

src/GraphQL/Schemas/Primary/Mutations/SetWalletAccountMutation.php, tests/Feature/GraphQL/Mutations/SetWalletAccountTest.php
Bug fix, Tests
___
- Added a new validation rule in `SetWalletAccountMutation` to prevent duplicate wallet public keys by checking existing entries in the database.
- Updated the test `test_it_will_fail_with_duplicated_address` to assert the error response as an array subset, ensuring the correct error message is returned for duplicate accounts.
___
<tr>
<td>
<details>
<summary><strong>SetWalletAccountMutation.php</strong><dd><code>Add validation to prevent duplicate wallet public keys</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/GraphQL/Schemas/Primary/Mutations/SetWalletAccountMutation.php
<li>Removed the rule for <code>account</code> validation from …
=> [PLA-1968] Prevent duplicate wallet public key

src/Services/Processor/Substrate/DecoderService.php
bug_fix
___
- Added a `return null` statement in the `safeSerialize` method to handle exceptions gracefully by returning `null` when serialization fails.
- This change ensures that the method has a consistent return type and improves error handling.
___
<tr>
<td>
<details>
<summary><strong>DecoderService.php</strong><dd><code>Add return null for exception handling in serialization</code>&nbsp; &nbsp; </dd></summary>
<hr>
src/Services/Processor/Substrate/DecoderService.php
<li>Added a return statement to handle cases where serialization fails.<br> <li> Ensures the function returns <code>null</code> if an exception is caught.<br>
</details>
</td>
<td><a …
=> [PLA-1974] Add return null

src/Services/Processor/Substrate/BlockProcessor.php
enhancement
___
- Reduced the retry limit in the `runOrWaitIfEmpty` function from 5 to 3 to potentially improve performance and reduce wait times.
- Adjusted the retry mechanism for fetching block data, which may affect how the system handles empty results.
___
<tr>
<td>
<details>
<summary><strong>BlockProcessor.php</strong><dd><code>Lower retry limit for block fetching mechanism</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Services/Processor/Substrate/BlockProcessor.php
<li>Reduced the retry limit from 5 to 3 in the <code>runOrWaitIfEmpty</code> function.<br> <li> Adjusted the retry mechanism …
=> Lower decoder retry to 3

src/Services/Processor/Substrate/Codec/Encoder.php
Bug fix
___
- Added a validation step to ensure that encoded data is in the correct hexadecimal format.
- Throws a `PlatformException` if the encoded data does not match the expected format, improving error handling.
- This change prevents invalid encoded data from being processed further in the system.
___
<tr>
<td>
<details>
<summary><strong>Encoder.php</strong><dd><code>Add validation and exception for invalid encoded data</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Services/Processor/Substrate/Codec/Encoder.php
<li>Added import for <code>PlatformException</code>.<br> <li> Implemented validation for encoded data format.<br> <li> Throws …
=> [PLA-1979] Throw exception on invalid encoded data

config/enjin-platform.php, config/enjin-runtime.php
configuration changes
___
- Updated the `spec-version` and `transaction-version` for `SUBSTRATE_ENJIN` to 1012 and 10, respectively.
- Updated the `spec-version` and `transaction-version` for `SUBSTRATE_ENJIN_RELAY` to 1032 and 10, respectively.
___
<tr>
<td>
<details>
<summary><strong>enjin-platform.php</strong><dd><code>Update spec and transaction versions in configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated <code>spec-version</code> and <code>transaction-version</code> for <code>SUBSTRATE_ENJIN</code>.<br> <li> Updated <code>spec-version</code> and <code>transaction-version</code> for …
=> [PLA-1982] Upgrade runtime & specs for mainnet

src/Rules/ImmutableTransaction.php, tests/Feature/GraphQL/Mutations/UpdateTransactionTest.php
bug_fix
___
- Fixed a bug in the `ImmutableTransaction` class where updates with the same hash were incorrectly failing.
- Added a condition to ensure that the validation only fails if the new hash value is different from the existing one.
___
<tr>
<td>
<details>
<summary><strong>ImmutableTransaction.php</strong><dd><code>Fix validation to allow updates with identical hash values</code></dd></summary>
<hr>
src/Rules/ImmutableTransaction.php
<li>Modified the validation logic to allow updates with the same hash.<br> <li> Added a condition to check if the new value is different before <br>failing.<br>
</details>
</td>
<td><a …
=> [PLA-1985] Allow update with same hash on UpdateTransaction

src/Services/Processor/Substrate/Codec/Decoder.php
Bug fix
___
- Added `try-catch` blocks to the `collectionStorageData` and `tokenStorageData` methods to handle exceptions when processing data.
- Updated the processing logic to attempt decoding with `V1010` version first and fallback to the previous version if an exception occurs.
- Imported `PHPUnit\Exception` to manage exceptions effectively.
___
<tr>
<td>
<details>
<summary><strong>Decoder.php</strong><dd><code>Add exception handling to storage data processing methods</code></dd></summary>
<hr>
src/Services/Processor/Substrate/Codec/Decoder.php
<li>Added exception handling for <code>collectionStorageData</code> and <br><code>tokenStorageData</code> …
=> [PLA-1986] Fixes storage parsing during migration

lang/en/deprecated.php, lang/en/mutation.php, src/GraphQL/Schemas/Primary/Substrate/Mutations/TransferBalanceMutation.php, src/GraphQL/Types/Input/Substrate/OperatorTransferParamsInputType.php, src/GraphQL/Types/Input/Substrate/SimpleTransferParamsInputType.php
enhancement, documentation
___
- Added deprecation messages for `keepAlive` parameter in `operator_transfer_token` and `simple_transfer_token` in language files.
- Commented out `deprecationReason` in GraphQL schema and input type files for `TransferBalance`, `OperatorTransferParams`, and `SimpleTransferParams`.
- Updated descriptions for `keepAlive` parameter in mutation files.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>deprecated.php</strong><dd><code>Add deprecation messages for transfer token parameters</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
lang/en/deprecated.php
<li>Added deprecation message for …
=> Adds deprecationReason to keepAlive & TransferBalance

src/Services/Processor/Substrate/BlockProcessor.php
enhancement
___
- Added a call to `Cache::forget` for `PlatformCache::CUSTOM_TYPES` in the `ingest` method to ensure that custom types are forgotten when the ingest process starts.
- This change helps in maintaining the integrity of the cache by clearing outdated custom types before starting a new ingest process.
___
<tr>
<td>
<details>
<summary><strong>BlockProcessor.php</strong><dd><code>Clear custom types cache at the start of ingest process</code>&nbsp; &nbsp; </dd></summary>
<hr>
src/Services/Processor/Substrate/BlockProcessor.php
<li>Added a call to <code>Cache::forget</code> to clear custom types cache.<br> <li> Ensures that custom types are …
=> [PLA-2004] Forget customTypes when ingest starts

src/CoreServiceProvider.php
Bug fix
___
- Fixed cache key generation by replacing `toSql()` with `toRawSql()` in the `cursorPaginateWithTotal` and `cursorPaginateWithTotalDesc` methods.
- Ensures that the cache key accurately reflects the raw SQL query, preventing potential caching issues.
___
<tr>
<td>
<details>
<summary><strong>CoreServiceProvider.php</strong><dd><code>Fix cache key generation in pagination macros</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/CoreServiceProvider.php
<li>Replaced <code>toSql()</code> with <code>toRawSql()</code> for cache key generation.<br> <li> Updated cache key logic in …
=> [PLA-2017] Fix total count cache key

src/Services/Processor/Substrate/Codec/Types/ListingStorage.json
enhancement
___
- Added a new `AuctionData` type to the `ListingStorage.json` file, which includes `startBlock` and `endBlock` fields.
- Enhanced the `ListingData` enum to incorporate the newly added `AuctionData` type.
___
<tr>
<td>
<details>
<summary><strong>ListingStorage.json</strong><dd><code>Add `AuctionData` type and enhance `ListingData` enum</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Services/Processor/Substrate/Codec/Types/ListingStorage.json
<li>Added <code>AuctionData</code> type with <code>startBlock</code> and <code>endBlock</code> fields.<br> <li> Enhanced the <code>ListingData</code> enum to include …
=> [PLA-2033] Add AuctionData back

database/migrations/2024_10_14_041141_add_index_to_syncables_table.php, src/CoreServiceProvider.php
enhancement
___
- Added a new migration to create an index on the `syncables` table to improve query performance.
- Registered the new migration in the `CoreServiceProvider` to ensure it is executed.
___
<tr>
<td>
<details>
<summary><strong>2024_10_14_041141_add_index_to_syncables_table.php</strong><dd><code>Add migration for indexing `syncables` table</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
database/migrations/2024_10_14_041141_add_index_to_syncables_table.php
<li>Added a new migration file to create an index on the <code>syncables</code> table.<br> <li> Implemented the …
=> [PLA-2009] Add index to syncables

src/Jobs/SyncMetadata.php, src/Models/Laravel/Attribute.php
Bug fix
___
- Improved error logging in `SyncMetadata` by changing the log entry to include the error message in an array format. This enhances the structure and readability of the log.
___
<tr>
<td>
<details>
<summary><strong>SyncMetadata.php</strong><dd><code>Improve error logging structure in SyncMetadata</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Jobs/SyncMetadata.php
<li>Modified error logging to include error message in an array.<br> <li> Improved the structure of the error log entry.<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/271/files#diff-f14c4b145f7736dac52ea …
=> [PLA-2023] Fix error logging

composer.json
enhancement
___
- Updated the `composer.json` file to change the version constraint for the `gmajor/sr25519-bindings` dependency from `^1.0` to `*`, allowing for more flexibility in version selection.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>composer.json</strong><dd><code>Update version constraint for gmajor/sr25519-bindings dependency</code></dd></summary>
<hr>
composer.json
<li>Updated the version constraint for <code>gmajor/sr25519-bindings</code> from <code>^1.0</code> <br>to <code>*</code>.<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/274/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34">+1 …
=> [Hotfix] Accept any gmajor version

src/Models/Laravel/Attribute.php
enhancement
___
- Added a `boot` method to the `Attribute` model to automatically dispatch the `SyncMetadata` job when an attribute is created or updated.
- The synchronization is triggered only if the attribute's `key` matches a specific value (`0x757269`).
- This enhancement ensures that metadata is kept in sync with attribute changes, improving data consistency.
___
<tr>
<td>
<details>
<summary><strong>Attribute.php</strong><dd><code>Implement automatic metadata synchronization on attribute changes</code></dd></summary>
<hr>
src/Models/Laravel/Attribute.php
<li>Added import for <code>SyncMetadata</code> job.<br> <li> Implemented <code>boot</code> …
=> [PLA-2023] Sync attribute when creating or updating

database/factories/TransactionFactory.php, database/migrations/2024_10_17_061240_add_managed_to_transactions_table.php, src/CoreServiceProvider.php, src/GraphQL/Schemas/Primary/Mutations/MarkAndListPendingTransactionsMutation.php, src/Models/Laravel/Transaction.php, src/Support/Account.php
enhancement, bug_fix
___
- Added a new `managed` attribute to the `Transaction` model and database schema to improve query performance.
- Created a migration to add the `managed` column to the `transactions` table, including setting default values and updating existing records.
- Simplified transaction filtering logic in GraphQL mutations by utilizing the new `managed` column.
- Enhanced the `Transaction` model to automatically set the `managed` attribute during creation and updates.
- Introduced a new method in the `Account` support class to determine if a public key is managed.
___
<tr>
<td>
<details> …
=> [PLA-2045] Improve query performance

src/Clients/Abstracts/HttpAbstract.php
enhancement
___
- Removed the `withoutVerifying()` method call from the HTTP client configuration in the `getClient` method of the `HttpAbstract` class.
- This change enhances the security by ensuring SSL certificates are verified during HTTP requests.
___
<tr>
<td>
<details>
<summary><strong>HttpAbstract.php</strong><dd><code>Remove `withoutVerifying()` from HTTP client configuration</code></dd></summary>
<hr>
src/Clients/Abstracts/HttpAbstract.php
<li>Removed <code>withoutVerifying()</code> method call from the HTTP client <br>configuration.<br>
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/277/files#diff-77c72a39fc283671cf9da …
=> [PLA-2023] Remove without verifying

database/factories/PendingEventFactory.php, src/Commands/SyncMetadata.php, src/Models/Laravel/Attribute.php, src/Services/Database/MetadataService.php, src/Services/Processor/Substrate/Codec/Codec.php, tests/Feature/GraphQL/Queries/GetPendingEventsTest.php, tests/Feature/GraphQL/Queries/GetTokenTest.php
___
- Introduced a constant `URL_ENCODED_KEY` in `Laravel\Attribute` to replace the hardcoded hex key.
- Updated `SyncMetadata` command to use the new constant instead of a hardcoded value.
- Modified model events in `Attribute` to utilize the constant for better maintainability.
- Updated test cases in `GetTokenTest` to use the constant, ensuring consistency across the codebase.
___
<tr>
<td>
<details>
<summary><strong>SyncMetadata.php</strong><dd><code>Use constant for URL encoded key in SyncMetadata</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Commands/SyncMetadata.php
<li>Added import …
=> [PLA-2023] Refactor constant

src/Services/Processor/Substrate/Codec/Types/RemoveAccountRuleData.json
bug_fix
___
- Removed the `RemoveAccountRuleDataV1010` object from the JSON codec definition.
- Simplified the codec structure by retaining only the `RemoveAccountRuleData` object.
___
<tr>
<td>
<details>
<summary><strong>RemoveAccountRuleData.json</strong><dd><code>Simplify RemoveAccountRuleData codec by removing V1010</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Services/Processor/Substrate/Codec/Types/RemoveAccountRuleData.json
<li>Removed the <code>RemoveAccountRuleDataV1010</code> object.<br> <li> Simplified the codec by keeping only <code>RemoveAccountRuleData</code>.<br>
</details>
</td>
<td><a …
=> [PLA-2057] Fix RemoveAccountRuleData codec

src/GraphQL/Schemas/Primary/Substrate/Mutations/MutateTokenMutation.php, src/GraphQL/Types/Input/Substrate/TokenMutationInputType.php, tests/Feature/GraphQL/Mutations/MutateTokenTest.php
Enhancement, Tests
___
- Added `anyoneCanInfuse` and `name` parameters to the `MutateTokenMutation` class, allowing for more flexible token mutations.
- Updated the mutation encoding logic to handle the new parameters, including converting `name` to a hex string.
- Enhanced validation rules to ensure the presence of at least one of the new or existing parameters.
- Extended the `TokenMutationInputType` to include `anyoneCanInfuse` and `name` fields.
- Implemented new tests to verify the functionality of the `anyoneCanInfuse` and `name` parameters, ensuring they are correctly processed and validated.
___
<tr>
<td>
<details> …
=> [PLA-2058] Add anyone can infuse

src/Events/Global/TransactionCreated.php, src/Events/Global/TransactionUpdated.php
enhancement
___
- Replaced the `address` field with `public_key` in both `TransactionCreated` and `TransactionUpdated` classes.
- Updated the fallback method to `Account::daemonPublicKey()` for obtaining the public key.
- Adjusted the condition checks to ensure `public_key` is not null before proceeding.
___
<tr>
<td>
<details>
<summary><strong>TransactionCreated.php</strong><dd><code>Replace address with public key in TransactionCreated</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Events/Global/TransactionCreated.php
<li>Replaced usage of <code>address</code> with <code>public_key</code>.<br> <li> Updated the fallback method to …
=> [PLA-2068] Fix event should go to public key channels

src/Services/Blockchain/Implementations/Substrate.php, src/Services/Processor/Substrate/Events/Implementations/MultiTokens/TokenCreated.php, tests/Feature/GraphQL/Mutations/CreateTokenTest.php
bug_fix
___
- Fixed the logic for setting the token mint cap type by removing the incorrect condition for 'COLLAPSING_SUPPLY'.
- Ensured that the cap type is correctly set only when 'SINGLE_MINT' is specified.
___
<tr>
<td>
<details>
<summary><strong>Substrate.php</strong><dd><code>Fix condition for setting token mint cap type</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Services/Blockchain/Implementations/Substrate.php
<li>Removed the condition checking for 'COLLAPSING_SUPPLY' in the if <br>statement.<br> <li> Ensured that only 'SINGLE_MINT' is checked for setting the cap type.<br> …
=> [PLA-2088] Fix collapsing supply

lang/en/validation.php
Bug fix
___
- Fixed a typo in the 'invalid_after' translation string in the English validation file.
___
<tr>
<td>
<details>
<summary><strong>validation.php</strong><dd><code>Fix typo in 'invalid_after' translation string</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
lang/en/validation.php
- Corrected a typo in the translation string for 'invalid_after'.
</details>
</td>
<td><a href="https://github.com/enjin/platform-core/pull/290/files#diff-31a31d40d62ce50b5e434f851645fcfd67a47eb50238e32468433a863a737182">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>
</table></td></tr></tr></tbody></table>
___
> 💡 …
=> [PLA-1946] Fix translation

src/Commands/RelayWatcher.php
Bug fix
___
- Adjusted the fee calculation in the `createDaemonTransaction` method to subtract a slightly higher value (`101000000000000000` instead of `100000000000000000`).
- Ensures that enough value is retained to cover teleporting fees, addressing potential underpayment issues.
___
<tr>
<td>
<details>
<summary><strong>RelayWatcher.php</strong><dd><code>Adjust fee calculation to ensure sufficient teleporting value</code></dd></summary>
<hr>
src/Commands/RelayWatcher.php
<li>Adjusted the fee calculation by increasing the subtracted value from <br><code>100000000000000000</code> to <code>101000000000000000</code>.<br> <li> Ensures sufficient value is …
=> [PLA-2115] Keep enough value to pay for teleporting fee

src/Services/Processor/Substrate/Codec/Types/Dispatch.json
Bug fix
___
- Fixed the type of `signature` in the `ExpirableSignature` structure from `[u8; 32]` to `H512` in the `Dispatch.json` file.
- This resolves potential issues with signature encoding and ensures compatibility with expected formats.
___
<tr>
<td>
<details>
<summary><strong>Dispatch.json</strong><dd><code>Fix signature type in `ExpirableSignature` definition</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Services/Processor/Substrate/Codec/Types/Dispatch.json
<li>Changed the type of <code>signature</code> in <code>ExpirableSignature</code> from <code>[u8; 32]</code> to <br><code>H512</code>.<br>
</details>
</td>
<td><a …
=> [PLA-1931] Fixes signature encoding

src/Services/Processor/Substrate/Codec/Types/TankStorage.json
enhancement
___
- Introduced a new dispatch rule kind `MinimumInfusion` to the `DispatchRuleKind` enum in `TankStorage.json`.
- Updated the `DispatchRuleStorage` enum to include `MinimumInfusion` with type `u128`.
___
<tr>
<td>
<details>
<summary><strong>TankStorage.json</strong><dd><code>Add `MinimumInfusion` dispatch rule to TankStorage</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Services/Processor/Substrate/Codec/Types/TankStorage.json
<li>Added a new dispatch rule kind <code>MinimumInfusion</code> to the <code>DispatchRuleKind</code> <br>enum.<br> <li> Added <code>MinimumInfusion</code> with type <code>u128</code> …
=> [PLA-2120] MinInfusion dispatch rule

src/Commands/Sync.php, src/GraphQL/Types/Scalars/DateTimeType.php, src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/TokenMutated.php
Bug fix
___
- Fixed the condition for checking `isCurrency` attribute.
- Updated logic to correctly compare `isCurrency` value.
___
<tr>
<td>
<details>
<summary><strong>TokenMutated.php</strong><dd><code>Fix `isCurrency` attribute condition logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Services/Processor/Substrate/Codec/Polkadart/Events/MultiTokens/TokenMutated.php
<li>Updated the condition for <code>isCurrency</code> attribute.<br> <li> Changed comparison logic to match expected structure.
</details>
</td>
<td><a …
=> [PLA-2145] Check the correct attribute for is_currency
